# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38aee2b7a83c9f55d0cb472249bde0b6ba0acd877a932bcbd5d6a4946ef1d7c24a49e1ee5f0024181f60151f810acf4a886624031fe89a23dce098161639334f

test:
  secret_key_base: 77b39df411c58f7ab3264c2092e7ffa46ff13faf10eaee7389e8a1fcea7f6a50fe890779fb31cb0e71dcd4e7b4efa8cdf3961db3b61a43d7c2b29151b3f4a025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
